// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-search-reindex-api/api"
	"github.com/ONSdigital/dp-search-reindex-api/models"
	"sync"
)

var (
	lockDataStorerMockAcquireJobLock   sync.RWMutex
	lockDataStorerMockCreateJob        sync.RWMutex
	lockDataStorerMockCreateTask       sync.RWMutex
	lockDataStorerMockGetJob           sync.RWMutex
	lockDataStorerMockGetJobs          sync.RWMutex
	lockDataStorerMockGetTask          sync.RWMutex
	lockDataStorerMockGetTasks         sync.RWMutex
	lockDataStorerMockPutNumberOfTasks sync.RWMutex
	lockDataStorerMockUnlockJob        sync.RWMutex
	lockDataStorerMockUpdateIndexName  sync.RWMutex
	lockDataStorerMockUpdateJobState   sync.RWMutex
)

// Ensure, that DataStorerMock does implement DataStorer.
// If this is not the case, regenerate this file with moq.
var _ api.DataStorer = &DataStorerMock{}

// DataStorerMock is a mock implementation of api.DataStorer.
//
//     func TestSomethingThatUsesDataStorer(t *testing.T) {
//
//         // make and configure a mocked api.DataStorer
//         mockedDataStorer := &DataStorerMock{
//             AcquireJobLockFunc: func(ctx context.Context, id string) (string, error) {
// 	               panic("mock out the AcquireJobLock method")
//             },
//             CreateJobFunc: func(ctx context.Context, id string) (models.Job, error) {
// 	               panic("mock out the CreateJob method")
//             },
//             CreateTaskFunc: func(ctx context.Context, jobID string, taskName string, numDocuments int) (models.Task, error) {
// 	               panic("mock out the CreateTask method")
//             },
//             GetJobFunc: func(ctx context.Context, id string) (models.Job, error) {
// 	               panic("mock out the GetJob method")
//             },
//             GetJobsFunc: func(ctx context.Context, offset int, limit int) (models.Jobs, error) {
// 	               panic("mock out the GetJobs method")
//             },
//             GetTaskFunc: func(ctx context.Context, jobID string, taskName string) (models.Task, error) {
// 	               panic("mock out the GetTask method")
//             },
//             GetTasksFunc: func(ctx context.Context, offset int, limit int, jobID string) (models.Tasks, error) {
// 	               panic("mock out the GetTasks method")
//             },
//             PutNumberOfTasksFunc: func(ctx context.Context, id string, count int) error {
// 	               panic("mock out the PutNumberOfTasks method")
//             },
//             UnlockJobFunc: func(lockID string)  {
// 	               panic("mock out the UnlockJob method")
//             },
//             UpdateIndexNameFunc: func(indexName string, jobID string) error {
// 	               panic("mock out the UpdateIndexName method")
//             },
//             UpdateJobStateFunc: func(state string, jobID string) error {
// 	               panic("mock out the UpdateJobState method")
//             },
//         }
//
//         // use mockedDataStorer in code that requires api.DataStorer
//         // and then make assertions.
//
//     }
type DataStorerMock struct {
	// AcquireJobLockFunc mocks the AcquireJobLock method.
	AcquireJobLockFunc func(ctx context.Context, id string) (string, error)

	// CreateJobFunc mocks the CreateJob method.
	CreateJobFunc func(ctx context.Context, id string) (models.Job, error)

	// CreateTaskFunc mocks the CreateTask method.
	CreateTaskFunc func(ctx context.Context, jobID string, taskName string, numDocuments int) (models.Task, error)

	// GetJobFunc mocks the GetJob method.
	GetJobFunc func(ctx context.Context, id string) (models.Job, error)

	// GetJobsFunc mocks the GetJobs method.
	GetJobsFunc func(ctx context.Context, offset int, limit int) (models.Jobs, error)

	// GetTaskFunc mocks the GetTask method.
	GetTaskFunc func(ctx context.Context, jobID string, taskName string) (models.Task, error)

	// GetTasksFunc mocks the GetTasks method.
	GetTasksFunc func(ctx context.Context, offset int, limit int, jobID string) (models.Tasks, error)

	// PutNumberOfTasksFunc mocks the PutNumberOfTasks method.
	PutNumberOfTasksFunc func(ctx context.Context, id string, count int) error

	// UnlockJobFunc mocks the UnlockJob method.
	UnlockJobFunc func(lockID string)

	// UpdateIndexNameFunc mocks the UpdateIndexName method.
	UpdateIndexNameFunc func(indexName string, jobID string) error

	// UpdateJobStateFunc mocks the UpdateJobState method.
	UpdateJobStateFunc func(state string, jobID string) error

	// calls tracks calls to the methods.
	calls struct {
		// AcquireJobLock holds details about calls to the AcquireJobLock method.
		AcquireJobLock []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// CreateJob holds details about calls to the CreateJob method.
		CreateJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// CreateTask holds details about calls to the CreateTask method.
		CreateTask []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobID is the jobID argument value.
			JobID string
			// TaskName is the taskName argument value.
			TaskName string
			// NumDocuments is the numDocuments argument value.
			NumDocuments int
		}
		// GetJob holds details about calls to the GetJob method.
		GetJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetJobs holds details about calls to the GetJobs method.
		GetJobs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Offset is the offset argument value.
			Offset int
			// Limit is the limit argument value.
			Limit int
		}
		// GetTask holds details about calls to the GetTask method.
		GetTask []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobID is the jobID argument value.
			JobID string
			// TaskName is the taskName argument value.
			TaskName string
		}
		// GetTasks holds details about calls to the GetTasks method.
		GetTasks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Offset is the offset argument value.
			Offset int
			// Limit is the limit argument value.
			Limit int
			// JobID is the jobID argument value.
			JobID string
		}
		// PutNumberOfTasks holds details about calls to the PutNumberOfTasks method.
		PutNumberOfTasks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// Count is the count argument value.
			Count int
		}
		// UnlockJob holds details about calls to the UnlockJob method.
		UnlockJob []struct {
			// LockID is the lockID argument value.
			LockID string
		}
		// UpdateIndexName holds details about calls to the UpdateIndexName method.
		UpdateIndexName []struct {
			// IndexName is the indexName argument value.
			IndexName string
			// JobID is the jobID argument value.
			JobID string
		}
		// UpdateJobState holds details about calls to the UpdateJobState method.
		UpdateJobState []struct {
			// State is the state argument value.
			State string
			// JobID is the jobID argument value.
			JobID string
		}
	}
}

// AcquireJobLock calls AcquireJobLockFunc.
func (mock *DataStorerMock) AcquireJobLock(ctx context.Context, id string) (string, error) {
	if mock.AcquireJobLockFunc == nil {
		panic("DataStorerMock.AcquireJobLockFunc: method is nil but DataStorer.AcquireJobLock was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	lockDataStorerMockAcquireJobLock.Lock()
	mock.calls.AcquireJobLock = append(mock.calls.AcquireJobLock, callInfo)
	lockDataStorerMockAcquireJobLock.Unlock()
	return mock.AcquireJobLockFunc(ctx, id)
}

// AcquireJobLockCalls gets all the calls that were made to AcquireJobLock.
// Check the length with:
//     len(mockedDataStorer.AcquireJobLockCalls())
func (mock *DataStorerMock) AcquireJobLockCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	lockDataStorerMockAcquireJobLock.RLock()
	calls = mock.calls.AcquireJobLock
	lockDataStorerMockAcquireJobLock.RUnlock()
	return calls
}

// CreateJob calls CreateJobFunc.
func (mock *DataStorerMock) CreateJob(ctx context.Context, id string) (models.Job, error) {
	if mock.CreateJobFunc == nil {
		panic("DataStorerMock.CreateJobFunc: method is nil but DataStorer.CreateJob was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	lockDataStorerMockCreateJob.Lock()
	mock.calls.CreateJob = append(mock.calls.CreateJob, callInfo)
	lockDataStorerMockCreateJob.Unlock()
	return mock.CreateJobFunc(ctx, id)
}

// CreateJobCalls gets all the calls that were made to CreateJob.
// Check the length with:
//     len(mockedDataStorer.CreateJobCalls())
func (mock *DataStorerMock) CreateJobCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	lockDataStorerMockCreateJob.RLock()
	calls = mock.calls.CreateJob
	lockDataStorerMockCreateJob.RUnlock()
	return calls
}

// CreateTask calls CreateTaskFunc.
func (mock *DataStorerMock) CreateTask(ctx context.Context, jobID string, taskName string, numDocuments int) (models.Task, error) {
	if mock.CreateTaskFunc == nil {
		panic("DataStorerMock.CreateTaskFunc: method is nil but DataStorer.CreateTask was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		JobID        string
		TaskName     string
		NumDocuments int
	}{
		Ctx:          ctx,
		JobID:        jobID,
		TaskName:     taskName,
		NumDocuments: numDocuments,
	}
	lockDataStorerMockCreateTask.Lock()
	mock.calls.CreateTask = append(mock.calls.CreateTask, callInfo)
	lockDataStorerMockCreateTask.Unlock()
	return mock.CreateTaskFunc(ctx, jobID, taskName, numDocuments)
}

// CreateTaskCalls gets all the calls that were made to CreateTask.
// Check the length with:
//     len(mockedDataStorer.CreateTaskCalls())
func (mock *DataStorerMock) CreateTaskCalls() []struct {
	Ctx          context.Context
	JobID        string
	TaskName     string
	NumDocuments int
} {
	var calls []struct {
		Ctx          context.Context
		JobID        string
		TaskName     string
		NumDocuments int
	}
	lockDataStorerMockCreateTask.RLock()
	calls = mock.calls.CreateTask
	lockDataStorerMockCreateTask.RUnlock()
	return calls
}

// GetJob calls GetJobFunc.
func (mock *DataStorerMock) GetJob(ctx context.Context, id string) (models.Job, error) {
	if mock.GetJobFunc == nil {
		panic("DataStorerMock.GetJobFunc: method is nil but DataStorer.GetJob was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	lockDataStorerMockGetJob.Lock()
	mock.calls.GetJob = append(mock.calls.GetJob, callInfo)
	lockDataStorerMockGetJob.Unlock()
	return mock.GetJobFunc(ctx, id)
}

// GetJobCalls gets all the calls that were made to GetJob.
// Check the length with:
//     len(mockedDataStorer.GetJobCalls())
func (mock *DataStorerMock) GetJobCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	lockDataStorerMockGetJob.RLock()
	calls = mock.calls.GetJob
	lockDataStorerMockGetJob.RUnlock()
	return calls
}

// GetJobs calls GetJobsFunc.
func (mock *DataStorerMock) GetJobs(ctx context.Context, offset int, limit int) (models.Jobs, error) {
	if mock.GetJobsFunc == nil {
		panic("DataStorerMock.GetJobsFunc: method is nil but DataStorer.GetJobs was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Offset int
		Limit  int
	}{
		Ctx:    ctx,
		Offset: offset,
		Limit:  limit,
	}
	lockDataStorerMockGetJobs.Lock()
	mock.calls.GetJobs = append(mock.calls.GetJobs, callInfo)
	lockDataStorerMockGetJobs.Unlock()
	return mock.GetJobsFunc(ctx, offset, limit)
}

// GetJobsCalls gets all the calls that were made to GetJobs.
// Check the length with:
//     len(mockedDataStorer.GetJobsCalls())
func (mock *DataStorerMock) GetJobsCalls() []struct {
	Ctx    context.Context
	Offset int
	Limit  int
} {
	var calls []struct {
		Ctx    context.Context
		Offset int
		Limit  int
	}
	lockDataStorerMockGetJobs.RLock()
	calls = mock.calls.GetJobs
	lockDataStorerMockGetJobs.RUnlock()
	return calls
}

// GetTask calls GetTaskFunc.
func (mock *DataStorerMock) GetTask(ctx context.Context, jobID string, taskName string) (models.Task, error) {
	if mock.GetTaskFunc == nil {
		panic("DataStorerMock.GetTaskFunc: method is nil but DataStorer.GetTask was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		JobID    string
		TaskName string
	}{
		Ctx:      ctx,
		JobID:    jobID,
		TaskName: taskName,
	}
	lockDataStorerMockGetTask.Lock()
	mock.calls.GetTask = append(mock.calls.GetTask, callInfo)
	lockDataStorerMockGetTask.Unlock()
	return mock.GetTaskFunc(ctx, jobID, taskName)
}

// GetTaskCalls gets all the calls that were made to GetTask.
// Check the length with:
//     len(mockedDataStorer.GetTaskCalls())
func (mock *DataStorerMock) GetTaskCalls() []struct {
	Ctx      context.Context
	JobID    string
	TaskName string
} {
	var calls []struct {
		Ctx      context.Context
		JobID    string
		TaskName string
	}
	lockDataStorerMockGetTask.RLock()
	calls = mock.calls.GetTask
	lockDataStorerMockGetTask.RUnlock()
	return calls
}

// GetTasks calls GetTasksFunc.
func (mock *DataStorerMock) GetTasks(ctx context.Context, offset int, limit int, jobID string) (models.Tasks, error) {
	if mock.GetTasksFunc == nil {
		panic("DataStorerMock.GetTasksFunc: method is nil but DataStorer.GetTasks was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Offset int
		Limit  int
		JobID  string
	}{
		Ctx:    ctx,
		Offset: offset,
		Limit:  limit,
		JobID:  jobID,
	}
	lockDataStorerMockGetTasks.Lock()
	mock.calls.GetTasks = append(mock.calls.GetTasks, callInfo)
	lockDataStorerMockGetTasks.Unlock()
	return mock.GetTasksFunc(ctx, offset, limit, jobID)
}

// GetTasksCalls gets all the calls that were made to GetTasks.
// Check the length with:
//     len(mockedDataStorer.GetTasksCalls())
func (mock *DataStorerMock) GetTasksCalls() []struct {
	Ctx    context.Context
	Offset int
	Limit  int
	JobID  string
} {
	var calls []struct {
		Ctx    context.Context
		Offset int
		Limit  int
		JobID  string
	}
	lockDataStorerMockGetTasks.RLock()
	calls = mock.calls.GetTasks
	lockDataStorerMockGetTasks.RUnlock()
	return calls
}

// PutNumberOfTasks calls PutNumberOfTasksFunc.
func (mock *DataStorerMock) PutNumberOfTasks(ctx context.Context, id string, count int) error {
	if mock.PutNumberOfTasksFunc == nil {
		panic("DataStorerMock.PutNumberOfTasksFunc: method is nil but DataStorer.PutNumberOfTasks was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		ID    string
		Count int
	}{
		Ctx:   ctx,
		ID:    id,
		Count: count,
	}
	lockDataStorerMockPutNumberOfTasks.Lock()
	mock.calls.PutNumberOfTasks = append(mock.calls.PutNumberOfTasks, callInfo)
	lockDataStorerMockPutNumberOfTasks.Unlock()
	return mock.PutNumberOfTasksFunc(ctx, id, count)
}

// PutNumberOfTasksCalls gets all the calls that were made to PutNumberOfTasks.
// Check the length with:
//     len(mockedDataStorer.PutNumberOfTasksCalls())
func (mock *DataStorerMock) PutNumberOfTasksCalls() []struct {
	Ctx   context.Context
	ID    string
	Count int
} {
	var calls []struct {
		Ctx   context.Context
		ID    string
		Count int
	}
	lockDataStorerMockPutNumberOfTasks.RLock()
	calls = mock.calls.PutNumberOfTasks
	lockDataStorerMockPutNumberOfTasks.RUnlock()
	return calls
}

// UnlockJob calls UnlockJobFunc.
func (mock *DataStorerMock) UnlockJob(lockID string) {
	if mock.UnlockJobFunc == nil {
		panic("DataStorerMock.UnlockJobFunc: method is nil but DataStorer.UnlockJob was just called")
	}
	callInfo := struct {
		LockID string
	}{
		LockID: lockID,
	}
	lockDataStorerMockUnlockJob.Lock()
	mock.calls.UnlockJob = append(mock.calls.UnlockJob, callInfo)
	lockDataStorerMockUnlockJob.Unlock()
	mock.UnlockJobFunc(lockID)
}

// UnlockJobCalls gets all the calls that were made to UnlockJob.
// Check the length with:
//     len(mockedDataStorer.UnlockJobCalls())
func (mock *DataStorerMock) UnlockJobCalls() []struct {
	LockID string
} {
	var calls []struct {
		LockID string
	}
	lockDataStorerMockUnlockJob.RLock()
	calls = mock.calls.UnlockJob
	lockDataStorerMockUnlockJob.RUnlock()
	return calls
}

// UpdateIndexName calls UpdateIndexNameFunc.
func (mock *DataStorerMock) UpdateIndexName(indexName string, jobID string) error {
	if mock.UpdateIndexNameFunc == nil {
		panic("DataStorerMock.UpdateIndexNameFunc: method is nil but DataStorer.UpdateIndexName was just called")
	}
	callInfo := struct {
		IndexName string
		JobID     string
	}{
		IndexName: indexName,
		JobID:     jobID,
	}
	lockDataStorerMockUpdateIndexName.Lock()
	mock.calls.UpdateIndexName = append(mock.calls.UpdateIndexName, callInfo)
	lockDataStorerMockUpdateIndexName.Unlock()
	return mock.UpdateIndexNameFunc(indexName, jobID)
}

// UpdateIndexNameCalls gets all the calls that were made to UpdateIndexName.
// Check the length with:
//     len(mockedDataStorer.UpdateIndexNameCalls())
func (mock *DataStorerMock) UpdateIndexNameCalls() []struct {
	IndexName string
	JobID     string
} {
	var calls []struct {
		IndexName string
		JobID     string
	}
	lockDataStorerMockUpdateIndexName.RLock()
	calls = mock.calls.UpdateIndexName
	lockDataStorerMockUpdateIndexName.RUnlock()
	return calls
}

// UpdateJobState calls UpdateJobStateFunc.
func (mock *DataStorerMock) UpdateJobState(state string, jobID string) error {
	if mock.UpdateJobStateFunc == nil {
		panic("DataStorerMock.UpdateJobStateFunc: method is nil but DataStorer.UpdateJobState was just called")
	}
	callInfo := struct {
		State string
		JobID string
	}{
		State: state,
		JobID: jobID,
	}
	lockDataStorerMockUpdateJobState.Lock()
	mock.calls.UpdateJobState = append(mock.calls.UpdateJobState, callInfo)
	lockDataStorerMockUpdateJobState.Unlock()
	return mock.UpdateJobStateFunc(state, jobID)
}

// UpdateJobStateCalls gets all the calls that were made to UpdateJobState.
// Check the length with:
//     len(mockedDataStorer.UpdateJobStateCalls())
func (mock *DataStorerMock) UpdateJobStateCalls() []struct {
	State string
	JobID string
} {
	var calls []struct {
		State string
		JobID string
	}
	lockDataStorerMockUpdateJobState.RLock()
	calls = mock.calls.UpdateJobState
	lockDataStorerMockUpdateJobState.RUnlock()
	return calls
}
